---
abstract: ~
author:
  - 'yumaito <ito-yuma@kayac.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jobeet
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
